sudo: required
dist: trusty
language: node_js
cache:
  directories:
    - node_modules
os:
  - linux
  - osx
node_js:
  - '4'
  - '5'
  - '6'
addons:
  # Without this, firefox is pre-installed but a super old version
  firefox: 'latest'

install:
  - npm install

# Read more here: https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start || echo \"Unable to start virtual display.\""

script:
  - npm run istanbul
  - npm run coveralls
  - if [[ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_OS_NAME" = "linux" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then
      npm run publish-docs master;
    fi
