sudo: required
dist: trusty
language: node_js
cache:
  directories:
    - node_modules
os:
  - linux
node_js:
  - '4'
  - '5'
  - '6'

install:
  - npm install

# Read more here: https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start || echo \"Unable to start virtual display.\""

script:
  - npm run test
  - npm run coveralls
  #- if [[ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_OS_NAME" = "linux" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then
  #    ./project/publish-docs.sh master;
  #  fi
